name: pytorch_env
channels:
  - conda-forge
  - pytorch  
  - nvidia/label/cuda-12.4.0  # Include this line only if you have a GPU
  - defaults
dependencies:
  - python=3.12
  - pytorch=2.5.1
  - typing-extensions=4.12.2
  - torchvision
  - torchaudio
  - cuda
  - numpy
  - scikit-learn
  - conda-lock
  - setuptools
