name: Iris CI

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  iris:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache conda
      uses: actions/cache@v4
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: |
          ~/conda_pkgs_dir
          ~/envs
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('environment.yml') }}

    - name: Set up Anaconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: false
        activate-environment: pytorch_env
        environment-file: environment.yml
        use-only-tar-bz2: true

    - name: Debug Environment
      run: |
        conda env list
        conda list
        python --version
    
    - name: Run iris
      run: |
        python iris_pytorch_example.py
   
    
