name: Iris CI

on:
  push:
    branches:
      - main


jobs:
  iris:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache conda environment
      uses: actions/cache@v4
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-

    - name: Set up Anaconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: pytorch-env
        environment-file: environment.yml
        auto-update-conda: false
        use-only-tar-bz2: true

    - name: Create conda packages directory
      run: mkdir -p ~/conda_pkgs_dir

    - name: Configure conda to use cached packages
      run: conda config --add pkgs_dirs ~/conda_pkgs_dir

    - name: Debug Environment
      run: |
        conda env list
        conda list
        python --version
   
