name: Iris CI

on:
  push:
    branches:
      - main


jobs:
  iris:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Anaconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: pytorch-env
        environment-file: environment.yml

    - name: Debug
      run: |
        conda env list
        conda list
