name: Iris CI

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  iris:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache conda
      uses: actions/cache@v4
      id: cache
      env:
        # Increase this value to reset cache if environment.yml has not changed
        CACHE_NUMBER: 1
      with:
        path: |
          ~/conda_pkgs_dir
          /usr/share/miniconda
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('environment.yml') }}

    - name: Set up Anaconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        activate-environment: pytorch_env
        environment-file: environment.yml
        use-only-tar-bz2: false

    - name: Debug Environment
      run: |
        conda env list
        conda list
        python --version
    
    - name: Run iris
      run: |
        python iris_pytorch_example.py | tee summary.txt
    
    - name: Upload Image as an Artifact
      uses: actions/upload-artifact@v4
      with:
        name: iris_model_graph
        path: iris_model_graph.png
    
    - name: Generate Step Summary
      run: |
        cat summary.txt >> $GITHUB_STEP_SUMMARY
        # echo "[Download Artifact](https://github.com/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID)" >> $GITHUB_STEP_SUMMARY


   
    
